[package]
name = "embed-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.33"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono", "tls-rustls"] }
dotenvy = "0.15"
secrecy = "0.10"
bluer = { version = "0.17", features = ["bluetoothd"] }
futures = "0.3"

# cargo build/run --release
[profile.release]
debug = 0
lto = 'fat'
opt-level = 3
